name: vendor_app
description: Kids Chuapal.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#kcvendor123
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_bloc: ^0.20.0
  # bloc: ^0.14.4

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  http: ^0.12.0+2
  dio:
  sqflite: ^1.1.6
  path_provider: ^1.1.2
  connectivity: ^0.4.5+1
  flutter_svg:
  progress_indicators:
  simple_animations: ^1.3.3
  cached_network_image:
  shimmer:
  google_maps_flutter:
  flutter_google_places:
  location: ^2.3.5
  geolocator:
  geocoder:
  numberpicker: 
  font_awesome_flutter:
  flare_flutter:
  image_picker: ^0.6.1
  pull_to_refresh:  ^1.5.5
  intl: ^0.16.0
  camera:
  toast: ^0.1.5
  percent_indicator:
  shared_preferences:
  file_picker:
  # file_utils:
  # simple_permissions:
  transparent_image:
  share:
  esys_flutter_share:
  open_file:
  flutter_cache_manager:
  http_parser:
  # package_info:
  auto_size_text:


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/kids.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/animation/
     - assets/animation/Filip.flr
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
     - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
